
export default {
    LogOut: {
        title: "Thoát đăng nhập",
        contentText: "Bạn có muốn thoát đăng nhập không?",
        agree: "Đồng ý",
        disagree: "Không đồng ý"
    },
    toolTip: {
        print: "In",
        excel: "Export"
    },
    Forbidden: {
        title: "Bạn không có quyền truy cập trang này"
    },
    NotFound: {
        title: "Nội dung không tìm thấy hoặc không tồn tại!"
    },
    Exception: {
        noData: "Không có dữ liệu"
    },
    Form: {
        // Validate User
        codeExcelErr: 'Sai định dạng mã code công trường!',
        noOption: "no options",
        maxLeng1000: 'Vui lòng nhập tối đa 1000 kí tự',
        maxLeng1000ContentRequest: 'Lý do xin phép không vượt quá 1000 ký tự',
        maxLeng255: 'Vui lòng nhập tối đa 255 kí tự',
        mangleng11: 'Vui lòng nhập tối đa 11 kí tự',
        max20: 'Vui lòng nhập giá trị nhỏ hơn hoặc bằng 20',
        max60: 'Vui lòng nhập giá trị nhỏ hơn 60',
        number: 'Vui lòng nhập số',
        lengPhone: 'Vui lòng tối đa 11 số',
        lengMoney: 'VUi lòng tối da 10 số',
        User: {
            leng_1_255: 'Vui lòng nhập chữ và số với độ dài 0-255 kí tự và không chứa khoảng trắng',
            leng_255: 'Độ dài',
            password: 'Vui lòng nhập chữ và số với độ dài dưới 18 kí tự và không chứa khoảng trắng',
            code: 'Vui lòng nhập chữ và số với độ dài 1-15 kí tự và không chứa khoảng trắng',
            name: 'Vui lòng nhập chữ độ dài 1-50 kí tự',
            min2: 'Vui lòng nhập lớn hơn 1 kí tự',
            maxLength15: "Vui lòng nhập nhỏ hơn 15 kí tự",
            phone: 'Vui lòng nhập số với độ dài 1-11 kí tự',
            number: 'Vui lòng nhập số nhỏ hơn hoặc bằng 20',
        },
        buttonOK: "OK",
        buttonClear: 'Clear',
        required: "Vui lòng nhập đầy đủ thông tin",
        min: "Vui lòng nhập giá trị nhỏ nhất là ${arguments[0]}",
        max: "Vui lòng nhập giá trị lớn nhất là ${arguments[0]}",
        minLength: "Vui lòng nhập tối thiểu ${arguments[0]} ký tự",
        maxLength: "Vui lòng nhập tối đa ${arguments[0]} ký tự",
        lessThan: "Vui lòng nhập giá trị nhỏ hơn ${arguments[0]}",
        greatherThan: "Vui lòng nhập giá trị lớn hơn ${arguments[0]}",
        incorrectPassword: "Tài khoản hoặc mật khẩu không chính xác. Nếu bạn đã quên thông tin, vui lòng liên hệ quản trị viên để được trợ giúp.",
        duplicateDate: "Ngày này đã tồn tại. Vui lòng chọn ngày khác !",
        pastDate: "Đây là ngày trong quá khứ. Vui lòng chọn ngày khác !",
        lessHour: "giờ phải nhỏ hơn giờ tiếp theo",
        userName: "vui lòng nhập từ 6 đến 16 ký tự bao gồm chữ cái và số!",
        noSpace: "Vui lòng không nhập khoảng trắng!"
    },
    Common: {
        start: "Bắt đầu",
        end: "Kết thúc",
        from: 'Từ',
        to: 'Đến',
    },
    Input: {
        choseDate: 'Lọc theo ngày', //
        filterDate: 'Chọn ngày', //
        hours: "Giờ",
        minutes: "Phút",
        Filter: "Lọc...",
        filter: "Lọc",
        password: "Mật khẩu",
        rePassword: "Nhập lại mật khẩu",
        date: "Ngày",
        name: "Tên nhân viên",
        code: "Mã Nhân viên",
        groupCode: "Mã nhóm",
        groupName: "Tên nhóm",
        title: "Tiêu đề",
        content: "Nội dung",
        user: {
            username: "Tên Đăng Nhập",
            code: 'Mã Nhân Viên',
            name: 'Tên Nhân Viên',
            phone: 'Số Điện Thoại',
            password: "Mật Khẩu",
            rePassword: "Nhập Lại Mật Khẩu",
            joining_date: 'Ngày tạo',
            dayOff: "有給繰越日数", //"Số ngày nghỉ có tính lương", 

        },
        changePassword: {
            title: "Thay đổi mật khẩu người dùng",
            // notice: "Khi thay đổi mật khẩu thì tài khoản của người dùng cũng sẽ",
        }
    },
    Button: {
        previews: 'Xem trước',
        line_account: "Tài khoản Line",
        changePassword: 'Đổi MK',
        chose: "Chọn",
        create: "Thêm",
        edit: "Sửa",
        delete: "Xóa",
        back: "Back",
        createUser: "Thêm người dùng",
        createGroup: "Tạo nhóm",
        ok: "OK",
        exit: 'Thoát',
        cancel: "Hủy bỏ",
        detail: "Chi tiết",
        detailReport: '詳細',
        search: "Tìm kiếm",
        filter: "Lọc",
        submit: "Xác nhận",
    },
    Sidebar: {
        office: 'Nội thất văn phòng',
        tableLivingRoom: 'Bàn trà phòng khách',
        tvCabinet: 'Tủ kệ Tivi',
        shoesCabinet: 'Tủ giày',
        wardrobe: "Tủ quần áo",
        finance: 'Tài chính',
        client: 'Khách hàng',
        posts: "Tin tức",
        order: "Quản lý đơn hàng",
        goods: "Quản lý hàng hóa",
        bad: 'Giường ngủ',
        diningRoom: 'Phòng bếp',
        tableEat: 'Bàn ăn',
        tableRestaurant: 'Bàn nhà hàng',
        question: 'Câu hỏi thường gặp',
        contact: 'Liên hệ',
        center: "Trang chủ",
        info: 'Giới thiệu',
        registration: 'Đăng kí nhận tin tức',
        partner: 'Đối tác',
        new: 'Tin tức',
        introduce: 'Giới thiệu',
        job: 'Ngành nghề',
        user: "Tài khoản",
        group: "Nhóm",
    },
    Breadcrumb: {
        postsChangeTable: 'Chọn vị trí bàn ăn',
        postsSizebad: 'Chọn kích thước giường',
        postsExport: 'Đạt tiêu chuẩn xuất khẩu',
        postsQuality: 'Tiêu chuẩn xuất khẩu',
        postsGuarantee: 'Bảo hành chu đáo',
        postsQuality: 'Tiêu chuẩn xuất khẩu',

        goodsIndex: 'Quản lý hàng hóa',
        goodsCreate: 'Thêm hang hoa',
        goodsEdit: 'Thêm hang hoa',

        orderIndex: 'Quản lý đơn hàng',
        orderCreate: 'Tạo đơn hàng',
        orderEdit: 'Sửa đơn hàng',

        financeIndex: 'Tài chính',
        financeCreate: 'Thên thông tin tài chính',
        financeEdit: 'Sửa thông tin tài chính',

        badIndex: 'Giường ngủ',
        tableEatIndex: 'Bàn ăn',
        tableRestaurantIndex: 'Bàn nhà hàng',
        wardrobeIndex: 'Tủ quần áo',
        shoesCabinetIndex: 'Tủ giày',
        tvCabinetIndex: 'Tủ kệ Tivi',
        tableLivingRoomIndex: 'Bàn trà phòng khách',
        officeIndex: 'Nội thất văn phòng',

        diningRoomIndex: 'Phòng bếp',
        centerIndex: 'Đồ gỗ nội thất Dodo',
        infoIndex: 'Giới thiệu',
        contactIndex: 'Liên hệ',
        registrationIndex: "Đăng kí",
        partnerIndex: 'Đối tác',
        introduceIndex: 'Giới thiệu',
        jobIndex: 'Công việc',
        newIndex: 'Tin tức',
        recruimentIndex: "Tuyển dụng",
        questionIndex: 'Câu hỏi thường gặp',

        userIndex: "Trang chủ",
        userCreate: "Thêm mới người dùng",
        userEdit: "Sửa thông tin người dùng",

        groupCreate: "Thêm mới nhóm",
        clientIndex: 'Khách hàng',

        notFound: "Không tìm thấy"
    },
    Table: {
        header: {
            row: "Hàng",
            index: "STT",
            code: 'Code',
            name: 'Tên',
            username: 'Tài Khoản',
            status: 'Trạng thái',
            createdAt: 'Ngày Tạo',
            action: 'Hành Động',
            content: "Nội dung",
            date: 'Ngày',
            dateRequest: "Ngày xin phép",
            allow: "Trạng thái",
            user: {
                username: "Tài Khoản",
                index: "STT",
                code: 'Mã Nhân viên',
                name: 'Tên Nhân viên',
                phone: 'Số Điện Thoại',
                positionCode: "Mã Chức Vụ",
                positionName: "Tên Chức Vụ",
                recruimentName: "Khu Vực",
                countUsed: "Số ngày nghỉ có lương đã sử dụng",
                remain: "Số ngày nghỉ có lương còn lại",
                remainByWorkingOnDayOff: "Số ngày nghỉ bù còn lại",
                dayOffInFuture: "Ngày Dự Định Nghỉ",
            },
            role: {
                code: 'Mã Vai Trò',
                name: 'Tên Vai Trò',
                userCount: 'Số lượng user',
            },
            position: {
                code: 'Mã Chức Vụ',
                name: 'Tên Chức Vụ',
                remuneration: 'Tiền Thù Lao',
                number: "Số lượng user",
            },
            recruiment: {
                code: 'Mã Khu Vực',
                name: 'Tên Khu Vực',
            },
            construction: {
                timeConstruction: 'Giờ làm tại công trường',
                totalPeople: "Tổng số người",
                totalDate: 'Tổng số ngày',
                totalProfit: 'Tổng Phí lao động',
                code: 'Mã Công Trường',
                name: 'Tên Công Trường',
                cost: 'Tiền hợp đồng',
                amount: 'Dự tính tiền công',
                userName: "Tên nhân viên",
                notCheckOut: "Chưa check out",
                startTime: 'Giờ đi làm thực tế',
                endTime: 'Giờ tan làm thực tế',
                dateStart: 'Ngày bắt đầu',
                dateEnd: 'Ngày kết thúc',
                _startTime: 'Giờ đi làm (Đã làm tròn)',
                _endTime: 'Giờ tan làm (Đã làm tròn)',
                date: 'Ngày',
                address: 'Địa chỉ',
                workTime: "Giờ làm việc",
                // workTime: "Giờ đi làm",
                workingTime: "Giờ đi làm",
                workingTimeInOut: "Giờ làm thực tế",
                _workingTimeInOut: "Giờ đã làm tròn",
                total: "Tổng",
                manage: "Người phê duyệt",
            },
            report: {
                title: "Tiêu đề",
                type: "Loại xin phép",
            },
            request: {
                dateDayOff: "getErrorTime thay thế",
                dateRequest: "Ngày xin phép",
                typeRequest: "Loại xin phép ",
                manage: "Người phê duyệt",
            },
            labor: {
                workTime: "Thời gian lao động tại công trường",
                laborTotal: "Tổng",
                totalWorkers: "Tổng số người",
                totalSalary: "Tổng phí lao động",
                profit: "Phí lao động tại công trường",
                detail: "chi tiết"
            },
            hour: {
                totalDays: "Số ngày đi làm",
                standardHour: "Số giờ làm việc trong thời gian làm việc tiêu chuẩn",
                morningOT: "Số giờ OT Sáng",
                nomalOT: "Số giờ OT bình thường",
                nightOT: "Số giờ OT đêm",
                statutoryDays_standardHour: "Số giờ làm việc trong thời gian làm việc tiêu chuẩn ngày nghỉ theo luật định",
                statutoryDays_morningOT: "Số giờ OT sáng sớm trong ngày nghỉ luật định",
                statutoryDays_nomalOT: "Số giờ OT bình thường trong ngày nghỉ luật định",
                statutoryDays_nightOT: "Số giờ OT đêm muộn trong ngày nghỉ luật định",
                nonStatutoryDays_standardHour: "Số giờ làm việc trong thời gian tiêu chuẩn ngày nghỉ ngoài quy định nhà nước",
                nonStatutoryDays_morningOT: "Số giờ OT sáng sớm trong ngày nghỉ ngoài luật định",
                nonStatutoryDays_nomalOT: "Số giờ OT bình thường trong ngày nghỉ ngoài luật định",
                nonStatutoryDays_nightOT: "Số giờ OT đêm muộn trong ngày nghỉ ngoài luật định",
                lateWork: "Đi muộn về sớm",
                totalTime: "Tổng thời gian lao động",
                rosteredDayOff: "Số ngày đã nghỉ bù"
            },
            timekeeping: {
                work_distance: "Khoảng cách di chuyển đi làm",
                personal_distance: "Khoảng cách di chuyển cá nhân",
                fuel: "Nhiên liệu đã dùng"
            }
        }
    },
    Message: {
        failedRequest: "Kiểm tra kết nối internet!",
        createDataSuccess: "Thêm mới dữ liệu thành công",
        crearteDataConstruction: "Thêm mới dữ liệu thành công",
        editDataSuccess: "Cập nhật dữ liệu thành công",
        deleteDataSuccess: "Đã xóa dữ liệu thành công",
        deleteDialogTitle: "Bạn có muốn xóa dữ liệu đã chọn không?",
        deleteDialogContent: "Dữ liệu sẽ không thể khôi phục sau khi xóa, vì vậy hãy cẩn trọng trong thao tác này.",
        deleteGroupDataSuccess: 'Xóa dữ liệu thành công',
        createGroupSuccess: "Thêm mới nhóm thành công",
        passwordNotMatch: "Mật Khẩu Không Khớp. Hãy Nhập Lại !",
        failHour: "Giờ nhập vào không chính xác, vui lòng xem lại !",
        userName: "Tên đăng nhập phải từ 6 đến 15 ký tự",
        erroeName: "Tên vai trò đã tồn tại",
        importExcel: "Bạn vừa thêm mới ${arguments[0]} công trường và update ${arguments[1]} công trường!",
        excelError: '${arguments[0]} công trường chưa đủ hoặc sai thông tin. Vui lòng xem lỗi bên dưới và cập nhật lại vào file excel gốc, sau đó bấm vào nút "Làm mới" để upload lại.'

    },
    User: {
        username: "Tài khoản",
        password: "Mật khẩu",
        remember: "Ghi nhớ tài khoản",
        signin: "Đăng nhập"
    },
  
    Backend: {
        DbObject: {
            Id_Required: "Id of Object is required",
            No_Object: "Object not found or Id is incorrect"
        },
        User: {
            User_Code_Exist: "Tên đăng nhập hoặc mã nhân viên đã tồn tại. \nVui lòng nhập tên hoặc mã khác",
            Del_User_Warn: "Bạn không thể xóa người dùng đã có lịch sử đi làm"
        },
        Recruiment: {
            Recruiment_Code_Exist: "Mã khu vực hoặc tên khu vực đã tồn tại. \nVui lòng nhập tên hoặc mã khác",
            Recruiment_Update_Warning: "Bạn không thể sửa khu vực này",
            Recruiment_Del_Warning: "Bạn không thể xóa khu vực này"
        },
    }
}